server:
  port: 3344
spring:
  application:
    name: cloud-config-center       #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:Zhou-JL/springcloud-config.git          #填写你自己的github路径
          uri: https://github.com/Zhou-JL/springcloud-config.git
          #搜索目录
          search-paths:
            - springcloud-config
          force-pull: true
          username: Zhou-JL
          password: zhou236513
      #读取分支
      label: main

  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#注册进Eureka服务器地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#rabbitmq相关配置
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'