server:
  port: 3366

spring:
  application:
    name: config-client
  cloud:
    #config 客户端配置
    config:
      label: main     #分支名称
      name: config    #配置文件名称
      profile: dev     #读取文件的后缀名称   上述3个： main分支上的 config-dev.yaml
      uri: http://localhost:3344   #配置中心地址    ，其实也是 http://config-3344.com:3344   ,因为在hosts 中做了映射

  #rabbitmq相关配置， 15672是web管理页面的端口，5672是MQ 访问的端口
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: "*"